package com.example.project_client.router;

public enum Pages {
    LOGIN_VIEW,ADMIN_VIEW, MAIN_VIEW,CREATE_ORDER_VIEW,CONFIRMATION_VIEW,ORDER_BILL_VIEW, CUSTOMER_VIEW,
    ADD_CUSTOMER_VIEW, UPDATE_CUSTOMER_VIEW, READ_CUSTOMER_VIEW

}
