package com.example.project_client.router;

public enum Pages {
    MAIN_VIEW,CREATE_ORDER_VIEW,
    CONFIRMATION_VIEW,
    ORDER_BILL_VIEW,
    MAIN_VIEW_PROFIT,
    SALARY_CAL_VIEW,
    BILL_INGREDIENT_CAL_VIEW,
    BILL_PRODUCT_CAL_VIEW,
    PROFIT_CAL_VIEW,
    PROMOTION_VIEW,
    SELECT_PRODUCT_FOR_PROMOTION_VIEW
}
