package com.example.project_client.router;

public enum Pages {
    MAIN_VIEW,CREATE_ORDER_VIEW,
    CUSTOMER_INFORMATION_INPUT_VIEW,
    ORDER_BILL_VIEW,
    MAIN_VIEW_PROFIT,
    SALARY_CAL_VIEW,
    BILL_INGREDIENT_CAL_VIEW,
    BILL_PRODUCT_CAL_VIEW,
    PROFIT_CAL_VIEW,
    PROMOTION_VIEW,
INGREDIENT_VIEW,ADD_INGREDIENT,CHANGE_INGREDIENT,PRODUCT_VIEW,ADD_PRODUCT,CHANGE_PRODUCT

}
